name = "multi_elevator"
description = "An almost complete simulation of the MULTI elevator"
version = "1.0.0"

authors = ["Thai Son Hoang"]
maintainers = ["Thai Son Hoang <T.S.Hoang@soton.ac.uk>"]
maintainers-logins = ["tshoang"]

executables = ["main"]
[[depends-on]]
gnatprove = "^12.1.1"
